export const allCharacters = {
    "001": {
        "rarity": "SSR",
        "photo": "/char/ssr_yue-ling.png",
        "name": "Yue Ling",
        "type": "Healer",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "-",
        "team": [],
        "desc": "Sua habilidade cura, limpa debuffs e ressussita (limite do ress é de uma vez a cada 5 turnos).",
        "descX": "Ganha pts de fúria para cada aliado sob efeito de controle."
    },
    "002": {
        "rarity": "SSR",
        "photo": "/char/ssr_xiao-xiao.png",
        "name": "Mr. XiaoYao",
        "type": "SubDPS",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "Back",
        "team": [],
        "desc": "Sua habilidade marca os inimigos da retaguarda, que causa dano adicional quando recebem dano de skill da sua party. Ao usar a habilidade, recupera pts de fúria para os aliados que atacam depois dele.",
        "descX": "Chance de causar silence."
    },
    "003": {
        "rarity": "SSR",
        "photo": "/char/ssr_xuan-lian-yin.png",
        "name": "Xuan Lian Yin",
        "type": "Suporte",
        "position": "Vanguarda",
        "Xatk": "1",
        "Xskill": "-",
        "team": [],
        "desc": "Sua habilidade garante um turno extra para a celebridade com maior ataque da party. Ao morrer, 50% dos seus pts de fúria são distribuídos entre os seus aliados. ",
        "descX": "Aumenta o ataque do aliado que recebe o turno extra."
    },
    "004": {
        "rarity": "SSR",
        "photo": "/char/ssr_lu-shu.png",
        "name": "Lu Shu",
        "type": "SubDPS",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "-1",
        "team": [],
        "desc": "Tanto seu ataque básico quanto a habilidade reduzem a fúria do alvo, respectivamente em 10 e 20 pts. Ataca novamente ao acertar crítico (ativa uma única vez por turno).",
        "descX": "Aumenta sua própria taxa crítica em 10%."
    },
    "005": {
        "rarity": "SSR",
        "photo": "/char/ssr_ye-yulan.png",
        "name": "Ye Yulan",
        "type": "Tank",
        "position": "Vanguarda",
        "Xatk": "1",
        "Xskill": "Front",
        "team": [],
        "desc": "Sua habilidade ataca a vanguarda, recupera HP, e absorve os pts de 'Espírito de Luta' acumulados, aumentando seu próprio ataque. Quanto mais tempo ele estiver em batalha, mais forte ele fica.",
        "descX": "Posicionar ele no meio da fileira."
    },
    "006": {
        "rarity": "SSR",
        "photo": "/char/ssr_shen-nanke.png",
        "name": "Shen Nanke",
        "type": "DPS",
        "position": "Ambos",
        "Xatk": "1",
        "Xskill": "1",
        "team": [],
        "desc": "Após usar a habilidade, entra em estado de 'Embriaguez', aumenta o ataque em 8% ( 3xTurnos ; Stack: 4 ). Também se esquiva do próx ataque recebido, e ganha 30 pts de fúria se derrotar o inimigo.",
        "descX": "Ignora 20% DEF no ataque básico."
    },
    "007": {
        "rarity": "SSR",
        "photo": "/char/ssr_agu-damu.png",
        "name": "Agu Damu",
        "type": "DPS",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "1-1",
        "team": [],
        "desc": "Ataca ambos os inimigos à sua frente. A cada rodada, há uma chance entrar no modo 'Focado', que aumenta ambos sua taxa crítica e dano crítico.",
        "descX": "Chance de atacar ambos os inimigos à sua frente no ataque básico também."
    },
    "008": {
        "rarity": "SSR",
        "photo": "/char/ssr_he-bi.png",
        "name": "He Bi",
        "type": "DPS",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "1",
        "team": [],
        "desc": "Ao usar sua habilidade ativa também o efeito da tinta recebida durante seu turno [Stack max de cada tinta : 6]. Verde : +Taxa crítica | Azul : + Redução de Dano | Vermelho : + Ataque ",
        "descX": "Ignora 20% DEF no ataque básico."
    },
    "009": {
        "rarity": "SSR",
        "photo": "/char/ssr_ying-er.png",
        "name": "Ying Er",
        "type": "Tank",
        "position": "Vanguarda",
        "Xatk": "1",
        "Xskill": "Back",
        "team": [],
        "desc": "Sua habilidade recae sobre a retaguarda inimiga + um inimigo aleatório. Precisa de bastante HP pois também fornece um escudo de 100% da própria vida que absorve o dano da habilidade dos inimigos. Não pode ser desfeito.",
        "descX": "-"
    },
    "010": {
        "rarity": "SSR",
        "photo": "/char/ssr_cheng-yun.png",
        "name": "Cheng Yun",
        "type": "Suporte",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "ALT",
        "team": [],
        "desc": "Aumenta o ataque dos aliados em 10% nos dois primeiros turnos. Sua habilidade tem como alvo o inimigo com maior ataque. Aplica o estado 'Suspeito' no alvo que diminui o ataque em 20% por 2 turnos.",
        "descX": "-"
    },
    "011": {
        "rarity": "SSR",
        "photo": "/char/ssr_dian-li.png",
        "name": "Dian Li",
        "type": "DPS",
        "position": "Retaguarda",
        "Xatk": "1",
        "Xskill": "AOE",
        "team": [],
        "desc": "Consegue se livrar de debuffs e ganhar 5 pts de fúria por cada. Sua habilidade causa dano equivalente a 80% do poder de ataque do time inimigo.",
        "descX": "Chance de 20% de aplicar o estado de 'Despacho', que reduz o ganho de fúria em 30%."
    }
}