export const allCharacters = {
    "001": {
        "rarity": "SSR",
        "photo": "/char/ssr_yue-ling.png",
        "name": "Yue Ling",
        "role": "Healer",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Sua habilidade cura, limpa debuffs e ressussita quem tiver maior ATK (limite do ress é de uma vez a cada 5 turnos). Com skill upada, caso o aliado esteja sob efeito de controle a cura é aumentada.",
        "descX": "Ganha pts de fúria para cada aliado sob efeito de controle quando entra no seu turno."
    },
    "002": {
        "rarity": "SSR",
        "photo": "/char/ssr_xiao-xiao.png",
        "name": "Mr. XiaoYao",
        "role": "SubDPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Back-Row",
        "team": "[\"Ji YuanQi\", \"Xuan Lian Yin\", \"Taoshan Ke\"]",
        "desc": "Sua habilidade marca os inimigos da retaguarda, que causa dano adicional quando recebem dano de skill da sua party. Ao usar a habilidade, recupera pts de fúria para os aliados que atacam depois dele.",
        "descX": "Chance de causar silence."
    },
    "003": {
        "rarity": "SSR",
        "photo": "/char/ssr_xuan-lian-yin.png",
        "name": "Xuan Lian Yin",
        "role": "Suporte",
        "position": "Vanguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[\"Ji YuanQi\", \"XiaoYao\", \"TaoShan Ke\"]",
        "desc": "Sua habilidade garante um turno extra para a celebridade com maior ataque da party. Ao morrer, 50% dos seus pts de fúria são distribuídos entre os seus aliados. ",
        "descX": "Aumenta o ataque do aliado que recebe o turno extra."
    },
    "004": {
        "rarity": "SSR",
        "photo": "/char/ssr_lu-shu.png",
        "name": "Lu Shu",
        "role": "SubDPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Single-Back",
        "team": "[\"Yu Ze\"]",
        "desc": "Ambos Atk básico e habilidade reduzem a fúria do alvo, respectivamente em 10 e 20 pts. Ataca novamente ao acertar crítico (ativa uma única vez por turno).",
        "descX": "Aumenta sua própria taxa crítica em 10%."
    },
    "005": {
        "rarity": "SSR",
        "photo": "/char/ssr_ye-yulan.png",
        "name": "Ye Yulan",
        "role": "Tank",
        "position": "Vanguarda",
        "Xatk": "Single-Front",
        "Xskill": "Front-Row",
        "team": "[\"ChenXiang\", \"He ZhiZhou\", \"Xuan Lian Yin\"]",
        "desc": "Sua habilidade ataca a vanguarda, recupera HP, e absorve os pts de 'Espírito de Luta' acumulados, aumentando seu próprio ataque. Quanto mais tempo ele estiver em batalha, mais forte ele fica.",
        "descX": "Posicionar ele no meio da fileira."
    },
    "006": {
        "rarity": "SSR",
        "photo": "/char/ssr_shen-nanke.png",
        "name": "Shen Nanke",
        "role": "DPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Single",
        "team": "[]",
        "desc": "Após usar a habilidade, entra em estado de 'Embriaguez'; aumenta o ataque em 8% por 3 turnos; esquiva do próximo ataque recebido. E ganha 30 pts de fúria se derrotar o inimigo.",
        "descX": "Ignora 20% DEF no ataque básico. Acúmulo máximo de 'Embriaguez' : 4."
    },
    "007": {
        "rarity": "SSR",
        "photo": "/char/ssr_agu-damu.png",
        "name": "Agu Damu",
        "role": "DPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Both",
        "team": "[\"004\", \"Xuan Lian Yin\"]",
        "desc": "Ataca ambos os inimigos à sua frente. A cada rodada, há uma chance entrar no modo 'Focado', que aumenta ambos sua taxa crítica e dano crítico.",
        "descX": "Chance de atacar ambos os inimigos à sua frente no ataque básico também."
    },
    "008": {
        "rarity": "SSR",
        "photo": "/char/ssr_he-bi.png",
        "name": "He Bi",
        "role": "DPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Single",
        "team": "[]",
        "desc": "Ao usar sua habilidade ativa também o efeito da tinta recebida durante seu turno.\\n\\nVerde : + Taxa crítica\\nAzul : + Redução de Dano\\nVermelho : + Ataque.",
        "descX": "Ignora 20% DEF no ataque básico.  Acúmulo máximo de cada tinta : 6."
    },
    "009": {
        "rarity": "SSR",
        "photo": "/char/ssr_ying-er.png",
        "name": "Ying Er",
        "role": "Tank",
        "position": "Vanguarda",
        "Xatk": "Single-Front",
        "Xskill": "Back-Row",
        "team": "[]",
        "desc": "Sua habilidade recae sobre a retaguarda inimiga + um inimigo aleatório. Precisa de bastante HP pois também fornece um escudo de 100% da própria vida que absorve o dano da habilidade dos inimigos.",
        "descX": "A imobilização da skill não pode ser desfeita."
    },
    "010": {
        "rarity": "SSR",
        "photo": "/char/ssr_cheng-yun.png",
        "name": "Cheng Yun",
        "role": "Suporte",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "ALT",
        "team": "[]",
        "desc": "Aumenta o ataque dos aliados em 10% nos dois primeiros turnos. Aplica o estado 'Suspeito' no alvo que diminui o ataque em 20% por 2 turnos.",
        "descX": "Sua habilidade tem como alvo o inimigo com maior ATQ."
    },
    "011": {
        "rarity": "SSR",
        "photo": "/char/ssr_dian-li.png",
        "name": "Dian Li",
        "role": "DPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "AOE",
        "team": "[]",
        "desc": "Consegue se livrar de debuffs e ganhar 5 pts de fúria por cada. Sua habilidade causa dano equivalente a 80% do poder de ataque do time inimigo.",
        "descX": "Chance de 20% de aplicar o estado de 'Despacho', que reduz o ganho de fúria em 30%."
    },
    "012": {
        "rarity": "R",
        "photo": "/char/r_qing-yin.png",
        "name": "Qing Yin",
        "role": "Suporte",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Em sua skill ele consome parte da própria vida para reduzir a barra de fúria de todos os inimigos. O valor depende do nível da habilidade.",
        "descX": "Reduz a barra de fúria do inimigo ao receber dano"
    },
    "013": {
        "rarity": "R",
        "photo": "/char/r_bai-ruier.png",
        "name": "Bai Ruier",
        "role": "Healer",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Cura os aliados com menor HP. Quando está com as skills upadas, o número de aliados curados aumenta.",
        "descX": "Ao entrar em batalha um pouco de fúria é recebida pelos aliados da mesma fileira."
    },
    "014": {
        "rarity": "R",
        "photo": "/char/r_yuan-hua.png",
        "name": "Yuan Hua",
        "role": "Healer",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Sua habilidade cura razoavelmente o aliado com menor HP.",
        "descX": "Após a cura, o aliado tem sua defesa aumentada."
    },
    "015": {
        "rarity": "R",
        "photo": "/char/r_taoshan-ke.png",
        "name": "TaoShan Ke",
        "role": "Suporte",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Sua habilidade consome 40% da própria vida para entregar 20 pts de fúria para todos os aliados. (Com exceção de si mesmo.)",
        "descX": "Ao atacar um inimigo, tem chance de 30% de aumentar a fúria dos aliados da mesma fileira em 10pts (Com exceção dele mesmo)."
    },
    "016": {
        "rarity": "SR",
        "photo": "/char/sr_he-zhizhou.png",
        "name": "He Zhizhou",
        "role": "Suporte",
        "position": "Vanguarda",
        "Xatk": "Single-Front",
        "Xskill": "NoDMG",
        "team": "[]",
        "desc": "Sua habilidade oferece escudo e limpa debuffs de controle da mesma fileira. O escudo deixa imune a controle. Com skill upada, inimigos que atacarem os escudos levarão Stun.",
        "descX": "Ao atacar um inimigo, retira 10pts de fúria e a entrega pada o aliado de maior ATQ."
    },
    "017": {
        "rarity": "SR",
        "photo": "/char/sr_xia-wanlian.png",
        "name": "Xia Wanlian",
        "role": "Control",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "Single",
        "team": "[]",
        "desc": "Sua habilidade ataca um único inimigo com chance de causar Stun de 50%. Valor aumenta conforme as skills são upadas.",
        "descX": "Após atacar, cura o aliado com menor HP em 50% do seu poder de ataque."
    },
    "018": {
        "rarity": "SR",
        "photo": "/char/sr_lin-shan.png",
        "name": "Lin Shan",
        "role": "SubDPS",
        "position": "Retaguarda",
        "Xatk": "Single-Front",
        "Xskill": "AOE",
        "team": "[]",
        "desc": "Aplica dois layers de veneno sobre os inimigos, causando dano de 20% de seu ATK sempre que entrar no turno dos inimigos afetados. Com skill upada também diminui a DEF do inimigo.",
        "descX": "Chance de 30% de adicionar um layer extra de veneno. Acúmulo máximo de veneno : 6. Pode ser removido."
    }
}